### ISSUE TITLE
Chapter 7: tensorboard.py ImportError SummaryWriter

### ISSUE THREAD

**Issue by MarcusFra** [falloutdurham/beginners-pytorch-deep-learning#20]
## ImportError

When I run the tensorboard.py I get the following ImportError:

```
Traceback (most recent call last):
  File "/home/marcus/Uebersezungen/beginners-pytorch-deep-learning/venv/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "/home/marcus/Uebersezungen/beginners-pytorch-deep-learning/chapter7/tensorboard.py", line 3, in <module>
    from torch.utils.tensorboard import SummaryWriter
ImportError: cannot import name 'SummaryWriter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorboard.py", line 3, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/marcus/Uebersezungen/beginners-pytorch-deep-learning/venv/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '
ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.
 marcus@marcus-XPS-13-7390  ~/Uebersezungen/beginners-pytorch-deep-learning/chapter7  master ✚ ● ?  python3 tensorboard.py                                                         1 ↵  478  15:58:52 
Traceback (most recent call last):
  File "/home/marcus/Uebersezungen/beginners-pytorch-deep-learning/venv/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "/home/marcus/Uebersezungen/beginners-pytorch-deep-learning/chapter7/tensorboard.py", line 3, in <module>
    from torch.utils.tensorboard import SummaryWriter
ImportError: cannot import name 'SummaryWriter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorboard.py", line 3, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/marcus/Uebersezungen/beginners-pytorch-deep-learning/venv/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '
ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.
```
## Versions

I work on Ubuntu 18.04 with tensorboard 2.2.1 and torch 1.4.0 installed

## My solution

I had to rename tensorboard.py to make it work, think it`s due to a naming conflict with the ```from torch.utils.tensorboard import SummaryWriter``` import, but maybe I`m wrong.

Does anyone have the same issue? Do I have the wrong dependencies installed?

**Comment by falloutdurham** [comment]
Should be fixed now!
